services:
  - type: web
    name: tic-tac-toe
    runtime: python-3.9.16  # Stable Python version
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free